config/routes.rb
SheetFromFacebookEvent::Application.routes.draw do

  root 'home#index'

  get '/list'     => "home#list"
  get '/generate' => "home#generate"
  post '/finish'  => "home#finish"
  get '/logout'    => "facebook#logout"
  namespace 'facebook' do
    get 'oauth'
    get 'callback'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
class BaseController < ApplicationController

  def facebook_oauth_required
    redirect_to facebook_oauth_path and return false if facebook_user.blank?
  end

  def facebook_logged_in?
    !facebook_user.blank?
  end

  def facebook_user
    graph = Koala::Facebook::API.new(session[:facebook_access_token])
    begin
      result = graph.get_object("/me/?locale=#{get_locale}")
      return (result=='false' ? {} : result)
    rescue Exception=>e
      return {}
    end
  end

  private

  def set_locale
    I18n.locale = get_locale
  end

  def get_locale
    session[:locale] ||= I18n.default_locale
  end

end

app/controllers/facebook_controller.rb
# -*- coding: utf-8 -*-
class FacebookController < BaseController

  def oauth
    oauth = Koala::Facebook::OAuth.new(Facebook::APP_ID, Facebook::APP_SECRET, Facebook::CALLBACK_URL)
    redirect_to oauth.url_for_oauth_code(:permissions => ['user_events'] )
  end

  def callback
    oauth = Koala::Facebook::OAuth.new(Facebook::APP_ID, Facebook::APP_SECRET, Facebook::CALLBACK_URL)
    if params[:code]
      session[:facebook_access_token] = oauth.get_access_token(params[:code])
    else
      # TODO : ERROR HANDLING
      flash[:error] = 'facebookログインに失敗しました'
      redirect_to :root and return
    end
      flash[:notice] = 'facebookログインに成功しました'

    redirect_to list_path
  end

  def logout
    session = nil

    redirect_to root_path
  end
end

app/controllers/home_controller.rb
# -*- coding: utf-8 -*-
class HomeController < BaseController
  before_action :facebook_oauth_required, :except => [:index]

  def index
  end

  def list
    graph = Koala::Facebook::API.new(session[:facebook_access_token])
    @event = graph.get_connections("me", "events", :fields => "attending, name", :locale => "ja_JP")
  end

  def generate
    @event_id = params[:event_id]
  end

  def finish
    graph = Koala::Facebook::API.new(session[:facebook_access_token])
    event = graph.get_object("#{params['event_id']}/?fields=attending,name,id&locale=ja_JP")

    session = GoogleDrive.login(params['google_id'], params['google_password'])
    ws = session.create_spreadsheet("#{event['name']}参加者一覧").worksheets[0]
    ws[1,1] = "参加者氏名"
    event['attending']['data'].each.with_index(2) do |member, index|
      ws[index, 1] = member['name']
    end
    ws.save
    flash['message'] = '作成しました。'
    redirect_to list_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/facebook_helper.rb
module FacebookHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/generate.html.erb
<h3>スプレッドシートを生成する情報を入力してください</h3>

<%= form_tag(finish_path, method: 'post') do %>
  <p>Google ID: <input type="text" name="google_id"/></p>
  <p>Google Password: <input type="password" name="google_password"/></p>
  <p><input type="hidden" value="<%= @event_id %>" name="event_id"/></p>
  <input type="submit" value="生成">
<% end %>

app/views/home/generate.thml.erb
<h3>スプレッドシートを生成するGoogleのIDを入力してください<h3>

app/views/home/index.html.erb
<a href="<%= facebook_oauth_path %>">facebook認証</a>

app/views/home/list.html.erb
<% if flash['message'] %>
  <h3><%= flash['message'] %></h3>
<% end %>

<% @event.each do |event| %>
<h2><%= event['name'] %></h2>
<p>日にち: <%= event['start_time'] %></p>
<a href="<%= generate_path(event_id: event['id'])  %>">スプレッドシートに名簿を作る</a>
<p>参加者</p>

<% event['attending']['data'].each do |member| %>
<p><%= member['name'] %></p>
<% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SheetFromFacebookEvent</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>